### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by yangyang5214** [yangyang5214/cuckoo#1]
when submit url  eg： https://www.baidu.com/

error is : 

```
2023-07-27 16:26:03,948 [cuckoo.core.guest] WARNING: cuckoo1: analysis #54 caught an exception
Traceback (most recent call last):
  File "C:/tmp78gx7m/analyzer.py", line 808, in <module>
    success = analyzer.run()
  File "C:/tmp78gx7m/analyzer.py", line 657, in run
    pids = self.package.start(self.target)
  File "C:\tmp78gx7m\modules\packages\ie.py", line 141, in start
    iexplore = self.get_path("Internet Explorer")
  File "C:\tmp78gx7m\lib\common\abstracts.py", line 79, in get_path
    for path in self.enum_paths():
  File "C:\tmp78gx7m\lib\common\abstracts.py", line 62, in enum_paths
    os.getenv("HomeDrive") + "\\",
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by yangyang5214** [comment]
还是我的问题。agent.py 不能通过计划任务启动，(环境变量不共享？)

命令行启动脚本正常运行。
